repos:
  - repo: local
    hooks:
      - id: build-check
        name: Build Check
        entry: bash -c 'cd /Users/javierdominguezsegura/Programming/S25/interships && make build'
        language: system
        pass_filenames: false
        always_run: true
