repos:
  - repo: local
    hooks:
      - id: build-check # Useful to check github actions will run
        name: Build Check
        entry: make build
        language: system
        pass_filenames: false
        always_run: true
