name: Build fronteng page and publish to github page
on:
      push:
            branches: [ main ]

permissions:
      contents: read
      pages: write
      id-token: write

jobs:
      deploy:
            runs-on: ubuntu-latest
            steps:
                  # Set-up
                  - name: "Checkout code"
                    uses: actions/checkout@v4
                  - name: "Setup Node"
                    uses: actions/setup-node@v4
                    with:
                      node-version: '18'
                  - name: "Setup Python"
                    uses: actions/setup-python@v4
                    with:
                      python-version: '3.12'
                  - name: "Install dependencies"
                    run: make install
                  
                  # Building frontend
                  - name: "Build frontend"
                    run: make build
                  
                  # Deploying artificat
                  - name: "Upload to artifact to the action"
                    uses: actions/upload-pages-artifact@v3
                    with:
                        path: ./frontend/dist
                  - id: deployment
                    uses: actions/deploy-pages@v4